apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-server
  labels:
    app: nginx-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          envFrom: 
          - configMapRef:
              name: nginx-config
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: static-media-volume
              mountPath: /usr/share/nginx/html/static
            - name: static-media-volume
              mountPath: /usr/share/nginx/html/media
              
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: static-media-volume
          persistentVolumeClaim:
            claimName: nginx-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service # Name of your Nginx service
  labels:
    app: nginx-static
spec:
  selector:
    app: nginx-static # This links the service to your Nginx pods
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 80 # The port your Nginx container is listening on
      name: http
    # - protocol: TCP
    #   port: 443
    #   targetPort: 443
    #   name: https
  type: LoadBalancer