version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6380:6379"
    networks:
      - app_network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 2 djangobackend.wsgi:application
    ports:
      - "8000:8000" 
    env_file: .env
    networks:
      - app_network
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A djangobackend worker -l info
    env_file: .env
    networks:
      - app_network
    depends_on:
      - redis
      - web # Depends on web if it needs to access Django models/database

  celery_beat:
    build: .
    command: celery -A djangobackend beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    env_file: .env
    networks:
      - app_network
    depends_on:
      - redis
      - web


networks:
  app_network:
    driver: bridge